### ISSUE TITLE
table - add merge of two separate layers

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1046]
Add functionality to combine two separate tables/layers into a single one. For example, this the case if there are two separate layers with counties in two states and we want to combine them into a single layer, or two point layers for two different time periods and we want to combine them. As a first step, the newly created table/layer could be saved as, or it would replace the current table/layer in the current project.

**Comment by YidanJ-Wu** [comment]
Windows 1.10.1.75
Verified

**Comment by jkoschinsky** [comment]
Right now, if you accidentally choose merge instead of stack, you get this error:

<img width="469" alt="screen shot 2017-09-27 at 11 53 26 am" src="https://user-images.githubusercontent.com/13679743/30926460-dc3cf990-a37a-11e7-94ae-cb59d376bd64.png">

After you OK this, the whole merge dialog changes, so you have to go back and re-specify everything. Instead, let's leave the merge table dialog open after OK'ing out of this view in case people want to choose stack instead

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.83 (OSX Yosemite, 10.10.5).
