### ISSUE TITLE
co-location map

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1060]
The idea is to add a map type to our list of maps, say under unique value map, 
called “co-location map”. One has to select more than one variable, each of which has to be integer,
similar to a unique value map. The map shows the locations where the values for the different 
variables (these are categorical, so it is up to the user to make sure they make sense) co-incide in a
location. For example, if one would compare the high-high, low-low etc. values between two LISA 
maps, one would specify the categories “saved” from the original LISA cluster map and enter those
as the co-location map variables. The resulting map would show as red the locations that are red in
both maps, etc. and gray out the locations that do not match.

**Comment by jkoschinsky** [comment]
For the LISA co-location map, let's add the LISA labels, e.g. to distinguish 0 = non-significant from others, which have the same color:

<img width="1699" alt="screen shot 2017-09-18 at 10 31 13 pm" src="https://user-images.githubusercontent.com/13679743/30574698-6d7eeef6-9cc1-11e7-933c-ec1b5322040f.png">

**Comment by jkoschinsky** [comment]
People usually don't know in advance which variables have co-located values. Let's change this text:

<img width="474" alt="screen shot 2017-09-18 at 10 22 36 pm" src="https://user-images.githubusercontent.com/13679743/30574710-89b956b0-9cc1-11e7-8f94-923d58624193.png">

to:
The categories of the selected variables do not overlap in space.
Please select other variables.

A better alternative could be to show a map without any co-location so people can see this result of no co-location, which often will be just as interesting as some colocation?

That way you always get a map instead of only getting a map in the presence of co-location.

**Comment by YidanJ-Wu** [comment]
Windows 1.10.1.77
I got to the stage of saving the categories from the LISA cluster maps. 
![image](https://user-images.githubusercontent.com/22801047/30892183-c4dda23c-a2fc-11e7-8372-8cf1c2dbf05c.png)
Handling of clicks seems to be off. When I clicked on the "select color scheme" button, the rent2008 variable would be selected instead. 
![image](https://user-images.githubusercontent.com/22801047/30892215-fae4f362-a2fc-11e7-942d-8d0e9ee81605.png)

**Comment by jkoschinsky** [comment]
Fix verified in GeoDa 1.10.1.79 (OSX Yosemite, 10.10.5).
except for others and significant have the same color for LISA map scheme:

<img width="606" alt="screen shot 2017-09-27 at 5 44 08 pm" src="https://user-images.githubusercontent.com/13679743/30941531-8af277d2-a3ab-11e7-8d3e-7b0f4a627c05.png">

**Comment by lixun910** [comment]
I leave them the same color, so you won't see too many colors in the
colocation map. You can change the color of "not significant" by clicking
on the color in the colocation setting dialog, or in the legend.

**Comment by jkoschinsky** [comment]
ok, works.
