### ISSUE TITLE
Crash: Centroids

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1084]
From: 
 Details:
os: 1-10-10
vs: 1-10-0-12
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
Shape_Area
Shape_Area
Open CartogramNewFrame.
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Project::GetVoronoiRookNeighborGal()
Project::GetVoronoiRookNeighborMap()
Project::IsPointDuplicates()
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()
Project::GetCentroids(std::vector<double>& x, std::vector<double>& y)
Project::GetCentroids()

**Comment by jkoschinsky** [comment]
I suspect this is data-specific since I can't replicate.

Steps I tried with point data (including duplicate XYs):
1. Read csv in
2. display and save centroids
3. save project file
4. get and save Thiessen polygons
5. create rook weights and explore connectivity map
5. open cartogram

also tried opening Thiessen polygon file
-- created rook weights and explored connectivity map

got no crash
