### ISSUE TITLE
Merge/Aggregate dialog size

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1140]
The size of the merge/aggregate dialog is too large to fit on a low resolution screen (e.g., with a VGA monitor). It is not possible to reach the "merge" or "aggregate" button at the bottom.

**Comment by lixun910** [comment]
Got it. Ancient projector has 640 (width) x 480 (height) resolution. That means many new dialog ui needs to be reorganized as well:
<img width="1282" alt="screen shot 2017-10-02 at 1 48 37 pm" src="https://user-images.githubusercontent.com/2423887/31098736-8103a338-a778-11e7-8dac-de1e0af139ce.png">

**Comment by lanselin** [comment]
we can keep the same designs, but maybe make the dialog scrollable so we can reach the bottom buttons

**Comment by lixun910** [comment]
Got it. Will try to do.

**Comment by lixun910** [comment]
Short version:  the Aggregate dialog has to be resized in XRC script. All other new dialogs (clustering) can be programmatically updated with scrolled window, so you can scroll down to the buttons when the screen resolution is not good to fit the whole dialog. 

Check new binary GeoDa 1.12.0.2:  https://www.dropbox.com/s/hgnt6ulfb4uilvg/GeoDa1.12.0.2-Installer.dmg?dl=0

<img width="825" alt="screen shot 2017-10-02 at 8 01 08 pm" src="https://user-images.githubusercontent.com/2423887/31109784-15e18e3c-a7b7-11e7-9caf-1b2447866741.png">

<img width="801" alt="screen shot 2017-10-02 at 9 18 45 pm" src="https://user-images.githubusercontent.com/2423887/31109824-4f5b1e08-a7b7-11e7-9910-2d262d4e887e.png">

**Comment by lixun910** [comment]
Also apply fix to colocation setting dialog

**Comment by VeraB620** [comment]
Haven't tested on low resolution screen (will do soon), but I was fiddling around making the box smaller on the normal screen and the right results page gets thinner and longer as I make the dialog bog smaller but not the Select Variables. Select Variable I can scroll in all 4 directions but the results only up and down. It would be nice if after a certain point that instead of getting thinner it can too go left and right.
<img width="413" alt="screen shot 2018-07-09 at 2 10 34 pm" src="https://user-images.githubusercontent.com/4943475/42471212-816cf4fa-8382-11e8-83aa-66ea3004e93c.png">

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.141

Working on 720p, scrolling does works
![screen shot 2018-07-10 at 1 12 13 pm](https://user-images.githubusercontent.com/4943475/42529184-5f23faee-8443-11e8-891d-abe792a99775.png)
![screen shot 2018-07-10 at 1 12 30 pm](https://user-images.githubusercontent.com/4943475/42529187-6374fb8e-8443-11e8-9ae8-58fe6d905221.png)
only aggregation does not scroll, but it stops at a certain size, won't get smaller
![screen shot 2018-07-10 at 1 12 59 pm](https://user-images.githubusercontent.com/4943475/42529205-7692ebcc-8443-11e8-95b1-f849636d7424.png)
