### ISSUE TITLE
Silent install switches won't remove old versions

### ISSUE THREAD

**Issue by teknowledgist** [GeoDaCenter/geoda#1241]
I understand why a "normal" install will open a dialog to remove an older install of GeoDa, but not why the dialog also opens when the `/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-` options are used (like for a deployment).

Please adjust the installer to auto-remove old versions when the obvious intent of the installing entity (i.e. a script scheduled by sysadmins) is to *make it silent* without user interaction.

**Comment by lixun910** [comment]
@teknowledgist GeoDa windows installer has some scripts to detect older installed GeoDa and asks user to do an uninstallation first. However, this can't be suppressed due to the limitation of Inno Setup, which was used to create the GeoDa installer.  

One workaround is you can add additional step to silently uninstall GeoDa first: e.g.
"C:\Program Files\GeoDa Software\unins000.ext" /VERYSLIENT

**Comment by teknowledgist** [comment]
That will do.  Thanks.
