### ISSUE TITLE
Freezing of time-grouped variables

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#1244]
From Julie:

The lab doesn't say that HRST and WHRST are time-grouped but I tried creating them as time-grouped variables (see below) and that worked fine. The calculator window froze when calculating HRST and WHRST, but unfroze after a few seconds.  

![image](https://user-images.githubusercontent.com/13679743/32120391-f48185ba-bb1d-11e7-9ae8-ade88da9c879.png)

From Xun:
I didn’t noticed this feature before (create a time grouped variable directly, not from the time editor). This might cause problems when one try to use it in maps and plots since it doesn’t contain any real variables when it’s created — looks like a concept of dummy time variable. Will test this feature more.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.29
The option to give a variable multiple time periods only shows up when there are other time grouped variables. Here's how the "add variable" window looks when there are no grouped variables:
![image](https://user-images.githubusercontent.com/22801047/32128123-03de47a0-bb41-11e7-96ef-a0c9889258e2.png)

Here's how it looks when other variables have been grouped in Time Editor:
![image](https://user-images.githubusercontent.com/22801047/32128161-3d25568e-bb41-11e7-8995-c6c6fd0d41ff.png)

I think the calculator window froze because of the dataset size. On smaller datasets that I've tried, it freezes for less than a second.

**Comment by lixun910** [comment]
I didn't see any point to keep such a feature in "Add Variable" dialog, since GeoDa already has "Time Editor" to create a grouped variable. 

I'd suggest to hide this option for user to create a dummy grouped variable.

**Comment by jkoschinsky** [comment]
Fix confirmed in GeoDa v111
OSX
