### ISSUE TITLE
Error in reading a spatialite table

### ISSUE THREAD

**Issue by anvalanz** [GeoDaCenter/geoda#1297]
![problems](https://user-images.githubusercontent.com/6723429/32609891-6bf43d02-c561-11e7-9d46-0fa148645e72.JPG)

When I read a spatialite table which has integer values for some fields on the first record then
all records of this fields have integer values regardless of the real values that are stored.

If I export the this table from spatialite to a shapefile and then read this shapefile with GeoDa everything is fine.

The attached screenshot describes the problem.
The upper table is one from  GeoDa , the lower is from spatialite_gui.

Regards
Antonio Valanzano

**Comment by lixun910** [comment]
@anvalanz  Can you try our latest GeoDa 1.12.1.43 to check if this has been addressed? Thanks!
https://www.dropbox.com/s/4ucuwa4okxx3tir/GeoDa-1.12.1.43-Windows-64bit.exe?dl=0

**Comment by anvalanz** [comment]
I have downloaded the version 1.12.1.43 as you suggested but nothing has changed.
I have also downloaded the latest version 1.12.1.47 from the website and nothing has changed as you can you see from the attached screen capture for the fields Icf2017, Tmor2017, Irpat2017:
![geoda_1_12_1_47](https://user-images.githubusercontent.com/6723429/32770362-9b3bb6c8-c91f-11e7-9dac-f46f3e2afeda.JPG)

By the way at the moment is not possible to download the 32 bit version.
See the attached error:
![error_download_32bit_version](https://user-images.githubusercontent.com/6723429/32770361-9b199412-c91f-11e7-8aeb-9871f3f1ff60.JPG)

A

**Comment by anvalanz** [comment]
I will wait for other instructions

**Comment by anvalanz** [comment]
I have already installed the proposed version and nothing has changed.



2017-11-12 5:17 GMT+01:00 Xun Li <notifications@github.com>:

**Comment by lixun910** [comment]
@anvalanz

Can you share your data with us, so I can replicate and fix this? I will keep it confidential. Thanks!

As you can see in my screenshot, the table loaded from a spatialite does look fine on my side.

**Comment by anvalanz** [comment]
Here is the link to the spatialite db

https://drive.google.com/open?id=0ByJcKzBj870QeENmdDA5Z0NhTWVzT0d1RHlIQVRhTUpVS0lV

Antonio

2017-11-17 17:36 GMT+01:00 Xun Li <notifications@github.com>:

> @anvalanz
>
> Can you share your data with us, so I can replicate and fix this? I will
> keep it confidential. Thanks!
>
> As you can see in my screenshot, the table loaded from a spatialite does
> look fine on my side.
>
>
>

**Comment by lixun910** [comment]
@anvalanz  Thanks for sharing you data! I was able to replicate this issue. It is caused by a new type "NUM" supported by Sqlite, which however is not supported by current gdal library used by GeoDa. 
 This is a screenshot of SQLite browser showing the data type of lcf2017 is "NUM". 
<img width="525" alt="screen shot 2017-11-20 at 3 48 57 pm" src="https://user-images.githubusercontent.com/2423887/33045649-d57c81ba-ce0a-11e7-9cb8-cab6c7ab30c9.png">

To workaround, you can explicitly change the data type to "REAL" in this sqlite file, which is officially supported by sqlite3 (see https://sqlite.org/datatype3.html). Then you should be able to load the table correctly in GeoDa. e.g.
<img width="527" alt="screen shot 2017-11-20 at 3 53 02 pm" src="https://user-images.githubusercontent.com/2423887/33045676-f0c88f18-ce0a-11e7-9a9a-fccebd7e390e.png">

**Comment by anvalanz** [comment]
Thanks for the information.
I hope soon the gdal library will support this new datatype.

Antonio


2017-11-20 23:53 GMT+01:00 Xun Li <notifications@github.com>:
