### ISSUE TITLE
k-means results not consistent

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1377]
The results given my k-means for the standard Guerry example are different in 1.12.1.61 from earlier versions. Compare the map and summary results below with the ones in the work book.

The bad news is that the "new" results are slightly worse than the ones before. What happened?

<img width="595" alt="screen shot 2017-12-03 at 10 12 59 am" src="https://user-images.githubusercontent.com/4008351/33527244-ea8451b6-d812-11e7-8670-00d9af72138b.png">
<img width="504" alt="screen shot 2017-12-03 at 10 12 52 am" src="https://user-images.githubusercontent.com/4008351/33527246-eda0519c-d812-11e7-916a-dea0911df603.png">

**Comment by lixun910** [comment]
Yes, I changed the parameter "initial re-runs" from 50 to 150, which is a parameter for KMeans++.

If you change it back to 50, I think you will get the same results as 1.12.1.59.

Xun

**Comment by lanselin** [comment]
Actually, with 50 the results are different, and worse than before.

<img width="478" alt="screen shot 2017-12-04 at 11 20 30 am" src="https://user-images.githubusercontent.com/4008351/33566369-5fc174a4-d8e5-11e7-86fe-6200cbd8fca8.png">

**Comment by lixun910** [comment]
Em, I just run it again using 1.12.1.63, and got same results as 1.12.1.59 (w.s.s. = 253.277) on both Mac and Windows (in virtual machine)…
Here are the screenshots:

**Comment by jkoschinsky** [comment]
@YidanJ-Wu could you check this since we're sometimes getting diverging results? thx

**Comment by lixun910** [comment]
I think I know what might cause the unstable KMeans issue. I rechecked the C cluster library code, and found that it’s random number generator is coded as a static function (globally defined) and is not thread-safe designed, that means in a multi-threaded case (which we used in GeoDa), calling this random number generator from multiple threads might return different sets of random numbers with same random seed, because the threads might mess up the seed value by change/update the global seed at the same time. I will fix this problem and get you another build.

Besides, here is something related to comparison of random and kmeans++ methods in R:

I did a further research on KMeans and KMeans++ using R. The Kmeans++ doesn’t always outperform random methods:

1. The R function kmeans is using “Hartigan-Wrong 1985” by default, and GeoDa only uses “Lloyd 1957”, which is same with scikit-learn
see: https://stat.ethz.ch/R-manual/R-devel/library/stats/html/kmeans.html
That’s why your R results is slightly better than GeoDa’s

2. The R library (LICORS) provides Kmeans with Kmeans++ method, which uses R function kmeans internally.

Here is the R script to compare:
<img width="648" alt="screen shot 2017-12-04 at 2 40 13 pm" src="https://user-images.githubusercontent.com/2423887/33627074-9eced392-d9b9-11e7-8250-efe71b947d91.png">

**Comment by lanselin** [comment]
Still not quite there. With 1.12.1.65, I noticed a strange type of cycling when changing the number of iterations with the random initialization. Depending on the number of initial runs, the solutions seems to be alternating between two optima, one slightly better than the other. For example, results for 50 give .497772, for 100 down to .497467, for 150 back to .497772, for 200 back to .497467, but 250, 300 and 500 all .497772. Results summary attached. This doesn't make sense since if the "best" starting point is among the first 50 runs, then it should never be worse for more initial runs, since they all include the same first 50 random solutions (with the same seed).

[summary2.txt](https://github.com/GeoDaCenter/geoda/files/1536964/summary2.txt)
