### ISSUE TITLE
median values in Box Plot and in Conditional Scatter Plot

### ISSUE THREAD

**Issue by anvalanz** [GeoDaCenter/geoda#1433]
Geoda 1.12.1.59 32 bit on Windows 7 enterprise
![median_values_in_box_plot_and_conditional_scatter_plot](https://user-images.githubusercontent.com/6723429/34165456-a1283aba-e4dc-11e7-8aa0-524720a22577.JPG)
Is there a specific reason for differences in median values between box plot and Conditional Scatter Plot ?
The  Q1 and Q3 value are the same (apart from rounding) in both graphs.

**Comment by lixun910** [comment]
in conditional scatter plot, the vert and horiz axes are quantile breaks Q1 Q2 Q3, not the same as box plot (Q1 median Q3)

**Comment by lixun910** [comment]
I thought it was percentile vs boxplot, will check again

**Comment by lixun910** [comment]
wont' fix: Compare to box-plot, the result of quantile (or quartile) will be the same if there are an even number of data points.  Otherwise, the algorithm will generate a slightly different break point to allow the median to be included in a subset. E.g. in your case: the break point in conditional plot is 2.703, so the median 2.7176 will be included in the 3rd subset.

see: https://en.wikipedia.org/wiki/Quartile

p.s. The algorithm used in GeoDa for k quantiles is computing (k-1) break values that divide the data set into k-subsets of nearly equal size. This is the same as pysal, which uses scipystats.scoreatpercentile.

<img width="848" alt="screen shot 2018-01-30 at 1 51 14 pm" src="https://user-images.githubusercontent.com/2423887/35590927-84b729d6-05c5-11e8-8173-cbad7ec1e810.png">
