### ISSUE TITLE
redesign distance weights interface

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1476]
The distance weight dialog is confusing as it is, since it now includes four different types of weights. That should be made clear, maybe with a thin separating line between them. Also, it would be better if the button below Threshold distance and Inverse distance would be indented as is the case for Adaptive Kernel.

Also, I suggest to rename "Threshold distance" to "Distance band" and re-order the weights with
Distance band first, K-Nearest neighbors next, and then Inverse distance and Adaptive kernel.

For inverse distance, the options should be similar to adaptive kernel, i.e., not just an overall bandwidth, but also the option of an adaptive bandwidth based on the number of nearest neighbors, using the same layout at for Adaptive kernel. It would help to list the max knn distance bandwidth explicitly next to that option, so that one could compare it to the max-min bandwidth.

Finally, the default number of neighbors for the adaptive kernel should be the cube root of the number of observations, following Kelejian and Prucha. So, for example, for natregimes that would be 15.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
### # **Donot** fixed yet

<img width="391" alt="10" src="https://user-images.githubusercontent.com/36253697/36703237-a181d500-1b52-11e8-99e0-8d7c76883752.PNG">

**Comment by jkoschinsky** [comment]
GeoDa 1.99
MacOSX

Still to be fixed:

Have four distance weights options:
- Distance band, K-Nearest neighbors, Inverse distance and Adaptive kernel (currently there are only three)
- Indent the button below Distance Band and Inverse distance as is the case for Adaptive Kernel.

For inverse distance, the options should be similar to adaptive kernel, i.e., not just an overall bandwidth, but also the option of an adaptive bandwidth based on the number of nearest neighbors, using the same layout at for Adaptive kernel. It would help to list the max knn distance bandwidth explicitly next to that option, so that one could compare it to the max-min bandwidth.

Finally, the default number of neighbors for the adaptive kernel should be the cube root of the number of observations, following Kelejian and Prucha. So, for example, for natregimes that would be 15. This is currently 14 (see below).

<img width="1112" alt="screen shot 2018-03-05 at 11 25 34 am" src="https://user-images.githubusercontent.com/13679743/36989680-0544512a-2068-11e8-919b-234a1494f957.png">

**Comment by lixun910** [comment]
@lanselin  as we discussed: there will be no "Inverse distance" tab, and instead, there is a check box 
   "x Use inverse distance? Power __" 
in tabs "Distance Band" and "K-Nearest Neighbors".

Let me know if this is correct.

**Comment by lanselin** [comment]
This is not how I described it above, but I can live with that design. However, the bandwidth seems to be incorrect. Using arc distance and miles it gives 1.46 and it should be something like 90.8 miles!

<img width="481" alt="screen shot 2018-03-05 at 11 38 42 am" src="https://user-images.githubusercontent.com/4008351/36995962-6e8b57d0-206a-11e8-81ac-b9ed4df15a1e.png">

**Comment by lanselin** [comment]
Also, the number of neighbors for kernel weights should be 15, not 14. The cube root of 3085 is 14.55, which should round to 15.

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.101
Verified 
<img width="779" alt="16" src="https://user-images.githubusercontent.com/36253697/37048683-809b6f9e-2166-11e8-8fef-a1893496e565.PNG">
