### ISSUE TITLE
Table: sorting column with empty values created from Local Join Count Map

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1506]
Steps: 

1. load guerry data
2. create gal weights
3. create Local Join Count map using m_gall
4. Save results
5. open table-> click "PP_VAL" column title to sort the column

<img width="198" alt="screen shot 2018-02-05 at 2 17 18 pm" src="https://user-images.githubusercontent.com/2423887/35829196-4ee5f170-0a7f-11e8-875b-e844c6e34d1c.png">

**Comment by lanselin** [comment]
unlike what I thought at first, the problem is for both ascending and descending sorts;
ascending starts with many empty rows, but then there are still empty rows interspersed
with the actual ones.

<img width="238" alt="screen shot 2018-02-05 at 1 21 46 pm" src="https://user-images.githubusercontent.com/4008351/35829416-aee4165e-0a77-11e8-9844-41583f07fdda.png">

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
Verified 

<img width="291" alt="08" src="https://user-images.githubusercontent.com/36253697/36702045-70329d7c-1b4d-11e8-9015-bedeff201728.PNG">

<img width="273" alt="09" src="https://user-images.githubusercontent.com/36253697/36702050-75bc7c04-1b4d-11e8-94b8-942f4001b9a0.PNG">

**Comment by jkoschinsky** [comment]
GeoDa 1.99
MacOSX
fix verified
