### ISSUE TITLE
something wrong with update logic

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1635]
Something seems to be wrong with the update logic. When checking for updates using version say 1.12.1.119, it gives version up to date, which it is not, since 1.12.1.125 is the latest. When checking for updates with a much older version, like 1.12.1.1, it gives an out of date version as the one to update to.

<img width="578" alt="geoda_update" src="https://user-images.githubusercontent.com/4008351/39251338-9e10d40a-4868-11e8-806b-9646bceb95ac.png">

**Comment by lixun910** [comment]
@lanselin It's because the auto-update for version 1.12.1.125 is not ready yet.   I need to make the auto-update patches manually for all platforms and then upload the patches to our AWS site. 

The current unstable auto-update version is 1.12.1.7, so any versions before 1.12.1.7 will be prompted to update to 1.12.1.7; and any version after 1.12.1.7 won't be prompted.

Will update them.

**Comment by jkoschinsky** [comment]
Am getting same "already up to date" message for GeoDa 1.12.1.129:

<img width="874" alt="screen shot 2018-06-06 at 11 11 29 am" src="https://user-images.githubusercontent.com/13679743/41050951-669538da-697a-11e8-93b0-cee39695e543.png">

Might be that later versions are internal only. Will leave open and add to discuss at next mtg.

**Comment by lixun910** [comment]
Will be working in 1.14
