### ISSUE TITLE
skater saved minimum spanning tree not added to weights manager

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1637]
When saving the MST from skater, the file is created, but it is not added to the weights manager. This contrasts with the behavior for the MDS weights, for example. This also means that an explicit load is needed to show the graph. The behavior should be the same as for MDS.

**Comment by YidanJ-Wu** [comment]
Windows 8 1.12.1.137
I got a similar error message after renaming the file to "columbus 0327"
The spanning tree saved correctly(attached). Presumably would not get the error message if the file name had no spaces (i.e. "columbus0327")
![image](https://user-images.githubusercontent.com/22801047/40731814-797a143a-63f7-11e8-9e51-b447be37e2ed.png)

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.141

When saving the MST it is added to weights manager
<img width="1168" alt="screen shot 2018-07-09 at 12 42 48 pm" src="https://user-images.githubusercontent.com/4943475/42466884-dea4661a-8375-11e8-9f47-556c39927cb6.png">


But there is no saving button for MDS
<img width="905" alt="screen shot 2018-07-09 at 12 44 01 pm" src="https://user-images.githubusercontent.com/4943475/42467269-12d55470-8377-11e8-968b-44ce589d67b5.png">


Also, as a  user, when selecting variables for both MST and MDS I had to hold the command button to be able to select more then one variable, it would be nicer if it was possible to do it without holding the command button since more then likely users will be selecting more then one variable.
