### ISSUE TITLE
Global Moran's I / Moran scatter plot with islands

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1654]
since the isolated value comes into play in computing the mean and variance.
GeoDa only supports row-standardized weights in the global Moran. Our solution is to eliminate the isolates from both numerator and denominator in the computation. The more fundamental point is that isolates do not contribute to any “spatial interaction” so they should not be included in any measure of spatial autocorrelation. For the local Moran etc. in GeoDa, this is already the case.

- issue warning “Moran scatter plot not supported when isolates are present”
- if user proceeds, we trim the island locations from the analysis, make sure the standardized
 values do not include the islands in the computation of mean and variance, and generate the
 scatter plot (with a warning that isolates have been removed)

**Comment by YidanJ-Wu** [comment]
Would this affect clustering algorithms that use weights files (SKATER, REDCAP)?

**Comment by lixun910** [comment]
No, this won’t affect clustering algorithms. I think we could apply different strategies, e.g. (ask user to choose) either connect islands to nearest to make a complete graph or remove islands in the background, to handle islands in clustering methods.

**Comment by Temisesba** [comment]
como puedo hacer lo mismo en rgeoda al hacer el scatter plot?

**Comment by jkoschinsky** [comment]
Hi, this is not in rgeoda because it is already implemented in R's spdep.
See here, e.g.: https://mgimond.github.io/Spatial/spatial-autocorrelation-in-r.html
I Spatial autocorrelation in R | Intro to GIS and Spatial Analysis - GitHub Pages<https://mgimond.github.io/Spatial/spatial-autocorrelation-in-r.html>
The data object consists of a SpatialPolygonsDataFrame vector layer, s1, representing income and education data aggregated at the county level for the state of Maine.. The spdep (Roger S. Bivand 2013) package used in this exercise makes use of sp objects including SpatialPoints* and SpatialPolygons* classes. For more information on converting to/from this format revert back to the Reading and ...
mgimond.github.io


Julia Koschinsky, Ph.D.
Executive Director and Senior Research Associate
Center for Spatial Data Science
University of Chicago
https://spatial.uchicago.edu/

<https://spatial-data-science-conference.com/>
________________________________
