### ISSUE TITLE
Connectivity: show selection and neighbors masks neighbor values

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1657]
In any map, Connectivity > Show selection and neighbors gives the neighboring locations a white color, so that their values cannot be seen. The neighbors should be shown with the original colors so that one can see the extent to which they are similar to the selected location/value. There should not be a "fill color for neighbors", or that could be an option, with "no fill" as the default.

<img width="275" alt="screen shot 2018-05-31 at 3 21 25 pm" src="https://user-images.githubusercontent.com/4008351/40806214-71cb8472-64e6-11e8-890e-0550d6691717.png">

**Comment by lixun910** [comment]
update fix in 08cbfcc

Note: the "fill color for neighbors" option is kept with "no fill" as the default, which is introduced in issue #1585 (see http://geodacenter.github.io/workbook/4a_contig_weights/lab4a.html figure 27)

To discriminate the selected and its neighbors, an option "Change Outline Color of Selected" is added for both Connectivity Map and Graph. The old "Change Outline Color of Neighbors" option for Connectivity Map only is removed.
<img width="506" alt="screen shot 2018-07-03 at 11 29 38 am" src="https://user-images.githubusercontent.com/2423887/42238053-81ce2090-7eb4-11e8-95e1-a977a66b727d.png">

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
tested GeoDa 1.12.1.137 and GeoDa 1.12.1.57

<img width="516" alt="screen shot 2018-07-03 at 10 31 14 pm" src="https://user-images.githubusercontent.com/37029239/42255401-26caea9a-7f11-11e8-948d-3de7907f0d93.png">
<img width="593" alt="screen shot 2018-07-03 at 10 31 03 pm" src="https://user-images.githubusercontent.com/37029239/42255402-270e497a-7f11-11e8-8d13-07355f55f467.png">

I was unable to find a way to display the values in the connectivity plot in version 1.12.1.137 (shown above)

In GeoDa version 1.12.1.57 (shown below) the values are still displayed for the neighbors but you can not click to see different neighbors without having to go back and select "Selection and Neighbors". Otherwise the neighbors will be unselected

<img width="248" alt="screen shot 2018-07-03 at 10 42 29 pm" src="https://user-images.githubusercontent.com/37029239/42255654-67597bac-7f12-11e8-9df7-9f01038dea51.png">
<img width="593" alt="screen shot 2018-07-03 at 10 40 20 pm" src="https://user-images.githubusercontent.com/37029239/42255655-67667762-7f12-11e8-970d-1ae176548ffa.png">

**Comment by lixun910** [comment]
Yes, the fix will be in the next release. I will let you know when it’s
ready. Thanks!

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.137

Change Outline Color of Selected works but I too have the old version of Change Outline Color of Neighbors is still there (same and ncarola)
The only way I way I was able to see their values was to change the opacity, which for an average user would not be very clear.

<img width="771" alt="screen shot 2018-07-05 at 10 44 38 am" src="https://user-images.githubusercontent.com/4943475/42333539-9d0e5d60-8040-11e8-8496-1fc35500e3b2.png">

**Comment by VeraB620** [comment]
OS X El Capitan 10.11.6
GeoDa 1.12.1.141

Default is no fill, but when I try to fill it, it does not apply.
<img width="494" alt="screen shot 2018-07-05 at 2 08 37 pm" src="https://user-images.githubusercontent.com/4943475/42342965-48224ba0-805d-11e8-850f-f204b7bed32d.png">
<img width="592" alt="screen shot 2018-07-05 at 2 05 31 pm" src="https://user-images.githubusercontent.com/4943475/42342969-4a37db76-805d-11e8-8b7c-0ea22d8f0a62.png">

**Comment by lixun910** [comment]
@VeraB620 Did you set the transparency of the fill color?
