### ISSUE TITLE
Crash Report: Running EDA on Excel table, crash with weights

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1660]
From: 
 Details:
os: 3-4-13
vs: 1-12-1-129
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::OnOkClick
ConnectDatasourceDlg::CreateDataSource()
Open Datasource:/home/luqasu/Workspace/PAMSI/project/gdansk_istatis.xlsx
Open Layer:gdansk_istatis
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::OnOkClick
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/home/luqasu/Workspace/PAMSI/project/gdansk_istatis.xlsx
Entering OGRTable::OGRTable
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnActivate
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnLabelLeftDClickEvent()
In TableFrame::OnActivate
Open DataMovieDlg.
Entering DataMovieDlg::OnFieldChoice
DataMovieDlg::OnPlayPauseButton
DataMovieDlg::OnPlayPauseButton
Close DataMovieDlg::OnClose
Open CatClassifFrame
CatClassifPanel::OnButtonNew
CatClassifPanel::OnButtonNew
CatClassifPanel::OnBreaksChoice
CatClassifPanel::OnAssocVarChoice
slotId
CatClassifPanel::OnBreaksChoice
CatClassifPanel::OnColorSchemeChoice
CatClassifPanel::OnBreaksChoice
CatClassifPanel::OnBreaksChoice
CatClassifPanel::OnBreaksChoice
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
MOR
Open HistogramFrame.
In HistogramFrame::OnActivate()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
SIZE
Open HistogramFrame.
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In TableFrame::OnActivate
Click GdaFrame::OnToolsWeightsManager
Entering WeightsManFrame::WeightsManFrame
In WeightsManFrame::SetDetailsForItem
Exiting WeightsManFrame::WeightsManFrame
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnActivate
In WeightsManFrame::OnCreateBtn
Click GdaFrame::OnToolsWeightsCreate
Open CreatingWeightDlg
Click CreatingWeightDlg::OnCThresholdTextEdit:
In WeightsManFrame::OnActivate
Click CreatingWeightDlg::OnIdVariableSelected

**Comment by jkoschinsky** [comment]
Not sure if they converted their Excel table to a map using XYs.

Steps to try to replicate:
1. open Excel table (doesn't have to have XYs)
2. run map movie
3. reclassify a variable using category editor
4. open histogram
5. try creating weights (since there's no spatial file, this shouldn't work)

If this doesn't lead to crash, try same steps with Excel file that has XYs: create point map using XY fields, then proceed with 2-5 (now weights creation will be available)

**Comment by ncarola** [comment]
macOS High Sierra 10.13.1
GeoDa 1.12.14.1

Replicated the above steps with both an excel map using x and y for the point map as well as non x and y variables. For each I was able to attempt to create a spatial weight but would give me the error that there are duplicate values. This happens because the reclassified variable is grouped into the specific breaks from the category editor. Therefore the variable would have the values of the break # they were in, i.e. either the 1st group = 1, 2nd group = 2, etc.
