### ISSUE TITLE
basemaps not loading

### ISSUE THREAD

**Issue by git74** [GeoDaCenter/geoda#1662]
Hi

I am new to GeoDa and I am trying to complete the "Spatial Data Handling" 
Workbook https://geodacenter.github.io/workbook/1_datascience/lab1.html. However, the basemaps were not displayed (both Carto and Nokia) when I added them (see below - first image). Clearing the basemap cache did not work either. When I checked the basemap cache, the .png were populated, but they were all of 0KB size (second image).

I have downloaded the files from here:  https://data.cityofchicago.org/Facilities-Geographic-Boundaries/Boundaries-Community-Areas-current-/cauq-8yn6 which, has prj files. 

![geoda base map issue](https://user-images.githubusercontent.com/23129513/41748283-45d7b18a-7605-11e8-9f4e-8c93da1f5da1.png)
![geoda basemap cache](https://user-images.githubusercontent.com/23129513/41748286-47b2c6ac-7605-11e8-8ed9-229fbff8707f.png)

**Comment by lanselin** [comment]
This is likely due to a problem with the projection information. Note that the spatial data handling exercise was specific to the U Chicago Intro Spatial Data Science class with some additional files made available to the students that are not on the web site. This particular exercise will be replaced by a more generic one, more broadly aimed at GeoDa users without dealing with the Chicago open data portal directly (the latter was a specific exercise for the class).

**Comment by git74** [comment]
Ok. Thanks for your reply.
Regards Anil

Sent from mobile 
 
  On Fri, 22 Jun 2018 at 10:42, Luc Anselin<notifications@github.com> wrote:   
This is likely due to a problem with the projection information. Note that the spatial data handling exercise was specific to the U Chicago Intro Spatial Data Science class with some additional files made available to the students that are not on the web site. This particular exercise will be replaced by a more generic one, more broadly aimed at GeoDa users without dealing with the Chicago open data portal directly (the latter was a specific exercise for the class).

**Comment by lixun910** [comment]
@git74 If it is not a projection issue, then I think this could be caused by windows firewall blocking GeoDa application. Can you access the carto tiles from https://carto.com/location-data-services/basemaps/ in a browser? 

If yes, then please check the windows firewall setting to make sure GeoDa is allowed to access internet.

If no, then your internet access is restricted to access the tile services provided by Carto and Nokia. You might need to contact your computer administrator.

Let me know if this helps. THanks!

**Comment by git74** [comment]
I have contacted our IT department and will provide an update soon. Thanks

**Comment by git74** [comment]
Hi lixun910
Could you please let me know the details of the ports or ip address settings and/or what is required to be done on the firewall so that I can load the basemaps?

Thanks
