### ISSUE TITLE
weights function enhancement

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#1751]
from Luc:

1.extend the distance weights functionality to higher dimensions, beyond 2
  right now, we have an x and y coordinate, which should remain the default, but
  it would be nice to be able to add more variables, so that a distance in multiattribute
  space could be computed
  - for example, this could create so-called socio-economic weights

2. generalize the distance metric beyond Euclidean distance, at the very least
  include Manhattan distance?

**Comment by lixun910** [comment]
v179

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.181 (macOS Mojave, 10.14.1). Dec. 10 build.

Enhancement verified: 
1. non-geographical distance allowed;
2. Manhattan distance added.

<img width="510" alt="1751" src="https://user-images.githubusercontent.com/45187310/50117422-8f65ef80-0212-11e9-87ea-cb012ee48a5e.png">

**Comment by lixun910** [comment]
@jkoschinsky I would leave it open, since I don't get feedback from Luc yet, and I am not sure if @Ashitacarl only verify the UI part, or did a throughout check at all the possible combinations and outputs of social weights creation.

**Comment by Ashitacarl** [comment]
@lixun910  and @jkoschinsky Sure I will test functionalities beyond the UI. Is there a routine/list to follow to check all the possible combinations using weights (GeoDa workbook?)?

**Comment by jkoschinsky** [comment]
@Ashitacarl -- great, thanks. There's no script to follow since this is new functionality, so just try to set it up so you increase the likelihood of breaking it (e.g. use grouped variables, table with missing values and any other data characteristics that aren't sample/text book data).

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.181 (macOS Mojave, 10.14.1). Dec. 17 build.

@lixun910 
Tested social distance weights. A few observations:
1. When creating the weight, GeoDa requires a distance metric specified: either Manhattan or Euclidean distance. I guess they are just "labels" or units in this case. Do we need to create another "distance metric" name for this social-distance purpose? Ex. Custom distance or social distance.

<img width="506" alt="1751-1" src="https://user-images.githubusercontent.com/45187310/50249668-45147800-03a4-11e9-87f0-675da39b4084.png">

2. In the weights manager dialogue, the "distance var" is not specified. Shall we include that? "Type" is specified as "threshold". I am not sure if this name is clear enough.

3. Also, in the same image, the min neighbor is 0, which should not be the case since I use the default distance bandwidth/threshold (guarantees at least one neighbor). Relatedly, when I change the bandwidth downward, I did not receive any warning message about creating isolates.

<img width="450" alt="1751-2" src="https://user-images.githubusercontent.com/45187310/50250143-9f620880-03a5-11e9-9936-e1c864d8fc83.png">

4. In Multivariate Local Geary's C Cluster Map, one cannot select multiple time points from a single group. Could this be a problem? The same is also found in Multivariate Local Join Count.

<img width="320" alt="1751-3" src="https://user-images.githubusercontent.com/45187310/50250999-0e406100-03a8-11e9-9cc9-1b17ea8a4e01.png">

No problem with grouped variables or table with missing values. No problem creating a project file. No problem with Moran scatter plots, Cluster Maps, Cluster Ana  I tested using datasets from external sources.

**Comment by lanselin** [comment]
The distance metric specifies how the distance in attribute space is calculated, nothing to do
with the “social” aspect of the distance. So should stay as is.

**Comment by lixun910** [comment]
@Ashitacarl  can you help to verify it? Thanks!

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.189 (macOS Mojave, 10.14.1). Jan. 15 build.

Datasets: Guerry sample and external.

One problem remains: when there are outliers in the distance var, GeoDa produces isolates. Also, missing values are problematic here. I don't know the underlying algorithm but observations with missing values seem to have a lot of neighbors. See figs and explanations below. 

All other fixed verified.

<img width="1090" alt="1791-3" src="https://user-images.githubusercontent.com/45187310/51238384-700ad100-193c-11e9-894b-d0f5cde2c46a.png">

In the first figure, the selected polygons have missing values (except the 1 obs) in the **distance var**. They seem to have a lot of neighbors (see column NUM_NBRS). The first selected polygon, as an outlier, has 0 neighbors. I used the default bandwidth, and no message pop up warning me of creating potential isolates (and it actually creates isolates). The figure below is another example of creating isolates without warning (default bandwidth used). The second example uses the Guerry sample data and '**Area**' variable as the **distance var**.

<img width="869" alt="1791-4" src="https://user-images.githubusercontent.com/45187310/51238402-79943900-193c-11e9-95fb-6861a572bc80.png">

**Comment by lanselin** [comment]
I need to check more carefully, but this could have something to do with the scale of the variable. Since all the distances are based on squared values and if the original values are large to begin with, there may be overflow issues.

One option would be to standardize all the variables before computing the distances, similar to what is done in the cluster modules.

**Comment by lixun910** [comment]
@Ashitacarl  Thanks! I was able to replicate this and found this bug: it happens when "manhanttan distance" is selected, the bandwidth is computed with square root, which is not correct and should only be applied when "Euclidean distance" is selected. This will be fixed in next build V191.

@lanselin Yes, this current implementation, the "Transformation:" options, which are the same with in cluster methods, have been added to allow user to scale the variables.
<img width="510" alt="screen shot 2019-01-16 at 10 21 26 am" src="https://user-images.githubusercontent.com/2423887/51266450-8afb3680-1978-11e9-85b1-ffe9bbed0a20.png">

**Comment by lixun910** [comment]
@Ashitacarl Empty values are not treated in current implementation.  This is not a problem when creating spatial weights since all geometries are valid, but a unique case in socio-weights creation. 

I think we simply treat observations with empty value "islands" when creating a socio-weights (will be in V191). Let me know if I am wrong @lanselin . Thanks!

**Comment by bsalas11** [comment]
GeoDa Windows 1.14

Fix verified. 

No errors detected in functionality. Warning appears to indicate the presence of isolates.

![Capture](https://user-images.githubusercontent.com/46054957/61984018-40621300-afc8-11e9-82eb-ef27e7589f82.PNG)

One potential quality of usage update: when selecting multiple distance weight variables, it would be nice to have it display more than three variables at a time. When the list of variables is lengthy, it becomes tedious to scroll up and down while having to remember the variables already selected. Perhaps have it turn into a drop-down list or allow the user to increase the size of the box to display more than three variables?

![variables](https://user-images.githubusercontent.com/46054957/61984216-0e9d7c00-afc9-11e9-928d-a9e374920fab.PNG)

**Comment by lixun910** [comment]
Fixed verified. The UI enhancement suggested by @bsalas11 is not supported by wxWidgets. Will keep an eye on possible enhancement.
