### ISSUE TITLE
Enhancement for Chinese translation

### ISSUE THREAD

**Issue by Polskamoze** [GeoDaCenter/geoda#1809]
![image](https://user-images.githubusercontent.com/33057199/52103175-0defd400-25aa-11e9-9683-98bb6cef1369.png)
At the bottom, "Selected" and "Unselected" are translated as "选择" and "未选中". It could be changed to "选择" and "未选择" to improve coherence.

**Comment by lixun910** [comment]
@Polskamoze  Thanks! Will change it in next release.

**Comment by lixun910** [comment]
<img width="573" alt="screen shot 2019-02-20 at 8 40 07 pm" src="https://user-images.githubusercontent.com/2423887/53142053-b9f46180-354f-11e9-90ec-755017c6447f.png">

V197

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.201 (macOS Mojave, 10.14.3). Feb. 20 build.

In the bottom, it is now consistently "选中", "未选中". However, at the top of the diag, there is "title" in English which is kinda weird. See below.

<img width="682" alt="1809" src="https://user-images.githubusercontent.com/45187310/53131740-33318b80-3533-11e9-90f6-f44fe5f72903.png">

**Comment by lixun910** [comment]
The label "Title" in selection tool dialog is actually a bug in wxWidgets 3.1.0. It has been reported in https://trac.wxwidgets.org/ticket/17410 and fixed in 
https://github.com/wxWidgets/wxWidgets/commit/98f5315405cf4cfc11ec3c7015146804267e67f7

The patch of this fix has been added to GeoDa repo. This issue will be fixed in V209.

**Comment by lixun910** [comment]
<img width="686" alt="Screen Shot 2019-03-18 at 10 06 22 PM" src="https://user-images.githubusercontent.com/2423887/54581454-166d6400-49ca-11e9-84e8-c762d47df4c3.png">

fixed in V209 and V211
