### ISSUE TITLE
GeoDa does not create distance based, knearest or any kind of weight matrices for pool data

### ISSUE THREAD

**Issue by firatgundem** [GeoDaCenter/geoda#1815]
First I opened time editor, grouped variables according to time. Secondly I save the grouped data as a dbf file. Finally I opened this dbf file as a pool data and tried many time to create weight matrices based on distance or k nearest. All of them failed. Even one of them didn't work. It does not allow you to chose STIC or other ID variables. After choosing them it does not create weight matrices.

**Comment by lixun910** [comment]
@firatgundem Are you trying to create weights using dbf (table-only) file? It will fail because there is no geometrical data associated with dbf. I suggest to use a .shp file with .dbf file (as well as a .shx file) to create a spatial weights file.

 Btw, we will also update the UI, so that when GeoDa loads a table-only data source, only "Variables" 
 based "Distance Weight" is enabled in Weights File Creation dialog.

**Comment by lixun910** [comment]
Step: load a table-only dataset, e.g. drag a .dbf file to GeoDa
one can click the "Create Weights" button, and the tab "Contiguity Weights" is enabled
create contiguity weights will fail.

Fix: when load a table-only dataset in GeoDa, "Create Weights Dialog" only allows users to create a "Variable" based weights. (in GeoDa V201)

**Comment by Ashitacarl** [comment]
GeoDa 1.12.1.201 (macOS Mojave, 10.14.3). Feb. 20 build.

Fix verified. The new UI now only allows table-only dataset to create weights based on table variables (e.g., lat long coordinate variables and social weights)
