### ISSUE TITLE
Crash: AMAP (Satellite) Basemap

### ISSUE THREAD

**Issue by bsalas11** [GeoDaCenter/geoda#1923]
Win: 1.14

Selecting the basemap AMAP (Satellite) leads to a crash or an inconsistent loading of the basemap.

![amap](https://user-images.githubusercontent.com/46054957/62810810-d3b93f00-bac4-11e9-9b81-e88bae53c31f.PNG)
![amap2](https://user-images.githubusercontent.com/46054957/62810811-d3b93f00-bac4-11e9-97ff-6aadafeb76ad.PNG)

Also, when selecting the basemap TianDiTu, no basemap appears (unsure if this is intentional and the maps are not available).

**Comment by lixun910** [comment]
Thanks, @bsalas11  I am looking at this issue now.

**Comment by lixun910** [comment]
@bsalas11 :  AMAP and TianDiTu are map tile services in China. I just checked that the inconsistent loading of the basemap from AMAP may be caused by the slow internet connection to the tile service provided by AMAP. I've updated the GeoDa setting with a connection timeout of 2 seconds (if no tiles can be downloaded). Can you help to use the latest build to check if there is no crash (which is our target :) with AMAP basemap?  (Windows: https://www.dropbox.com/s/y15tthfj3y46h15/GeoDa-1.14.0.0-Windows-64bit.exe?dl=0)

The TianDitu map tile service has been changed and it requires an app key which we can't obtain unless using a Chinese cell phone number, so it will be removed in GeoDa 1.14. Please don't test TianDiTu basemap. 

Let me know any issues and questions. Thanks!

**Comment by bsalas11** [comment]
Win 1.14

AMAP Basemap:
No crash or lag experienced with the new build.
