### ISSUE TITLE
example of shapefile where basemap is not displaying

### ISSUE THREAD

**Issue by GoogleCodeExporter** [GeoDaCenter/geoda#193]
```
GeoDa 1.7.35 (beta 1 July 2015)

See email of July 8, 2015 for link to shapefile.

"This county-level dataset has a .prj file but the basemap won't load. When you 
try to load it the map is reduced to a point."
```

Original issue reported on code.google.com by `jkosc...@asu.edu` on 8 Jul 2015 at 2:20

**Comment by jkoschinsky** [comment]
If you resize the map view, the basemap is still being duplicated (see attached) but it's better than before. I'm attaching shapefile in next comment. FYI in case there's a fix, otherwise we can close this ticket.

![screen shot 2015-11-09 at 5 47 10 pm](https://cloud.githubusercontent.com/assets/13679743/11049114/0732a67a-870a-11e5-96eb-52d216d6400b.png)

**Comment by lixun910** [comment]
keep current solution and leave it to future release
