### ISSUE TITLE
Missing Chinese translation

### ISSUE THREAD

**Issue by Polskamoze** [GeoDaCenter/geoda#1944]
In the Windows x64 version, the calculator page lacks Chinese translations for the buttons. 
![Calculator_Lacking_Chinese_Translation](https://user-images.githubusercontent.com/33057199/64682665-7003a680-d4b4-11e9-818b-d20d062a6b02.PNG)

**Comment by Polskamoze** [comment]
![捕获](https://user-images.githubusercontent.com/33057199/65009164-678cef00-d93e-11e9-9e64-7fad70f5cc9f.PNG)

In conditional scatterplots, the description could be translated from "dep. var" to "因变量"，“ind. var” to "自变量"，“horiz cat var” to "横轴分类变量"，and "vert cat var" to “纵轴分类变量”

**Comment by lixun910** [comment]
Thanks, @Polskamoze Will update the translations.

**Comment by lixun910** [comment]
Fixed in new GeoDa 1.14 build: https://www.dropbox.com/s/y15tthfj3y46h15/GeoDa-1.14.0.0-Windows-64bit.exe?dl=0

<img width="616" alt="Screen Shot 2019-09-25 at 7 17 35 PM" src="https://user-images.githubusercontent.com/2423887/65653208-36a95b80-dfc9-11e9-9de3-fd75ea3d5922.png">
<img width="701" alt="Screen Shot 2019-09-25 at 7 18 02 PM" src="https://user-images.githubusercontent.com/2423887/65653212-37da8880-dfc9-11e9-8236-fed584815ffd.png">
