### ISSUE TITLE
Multiple Enhancements for Chinese Translation

### ISSUE THREAD

**Issue by Polskamoze** [GeoDaCenter/geoda#1950]
![image](https://user-images.githubusercontent.com/33057199/65007324-55a84d80-d938-11e9-8e6d-020018142694.png)
In Windows x64 Chinese version, 
Under bubble charts, the right-click menu translates "unique value" as "唯一值", which could be changed to "特殊值".

**Comment by Polskamoze** [comment]
![image](https://user-images.githubusercontent.com/33057199/65023190-e7c64b00-d964-11e9-90cd-5f0b4dec1fa5.png)
Windows x64 Chinese version
On the upper left side, the "zoom in" button shows "缩小" for the choropleth mapping section, which needs to be changed to "放大". In addition, while the "zoom out" button works, the "zoom in" button is unable to work.

**Comment by lixun910** [comment]
Thanks, @Polskamoze 
1. "Unique value" means non-duplicated values: e.g. original values are 1,2,1,3,1 --> unique values are 1,2,3. So it better to be translated to "唯一值", instead of "特殊值".

2. Will update the translation text for "zoom in"

3. To "zoom in", one needs to select a "zoom in" area instead of left click, which works for "zoom-out".

**Comment by lixun910** [comment]
fixed in new GeoDa 1.14 build: https://www.dropbox.com/s/y15tthfj3y46h15/GeoDa-1.14.0.0-Windows-64bit.exe?dl=0

<img width="166" alt="Screen Shot 2019-09-25 at 7 14 25 PM" src="https://user-images.githubusercontent.com/2423887/65653072-c4d11200-dfc8-11e9-999a-253f5729e40f.png">

**Comment by Polskamoze** [comment]
Thanks! The Zoom in option tutorial could be added to the instruction manual since this operation hasn't been mentioned.
