### ISSUE TITLE
Saving to SQLite causes problems on re-reading

### ISSUE THREAD

**Issue by pkoppstein** [GeoDaCenter/geoda#1974]
Working through the "Lab1" tutorial (https://geodacenter.github.io/workbook/1_datascience/lab1.html) I ran
into a problem.  All went well up to but excluding the step beginning:

"Now we select dBase Database File, as shown."

Instead of choosing dBase, I chose SQLite.  This resulted in two additional tables
being added (geometry_columns, and spatial_ref_system).  In itself that looks harmless
enough, but after starting a new GeoDa session and selecting the file that was just created,
one is forced to choose between the three "layers". If I select the 
311_Service_Requests_-_Abandoned_Vehicles table, the table looks OK
but the map is wrong:

![311_Service_Requests--read from SQLite](https://user-images.githubusercontent.com/172847/66521525-58bad780-eab9-11e9-98c0-f2ad28531d2e.png)

Unfortunately, the various workarounds I've tried are too uninspired to bear documenting, but in case it helps, I'm using Mac OSX 10.13.6.

Thank you.

**Comment by lixun910** [comment]
@pkoppstein I think it is caused by some records without geometries (lat/lng or x/y) when you export to SQLITE file. To get the map with only valid geometries, you can select the points on the left side of the map, and then use the menu "File->SaveAs" to save the selected points to a new SQLITE file. Then, you should have be able to get the map you expected when opening the new SQLITE file in GeoDa.  Let me know if this works.

The points on the right side of the map are some points without geometry information but coded as (lat 0, lng 0) in SQLITE file.

**Comment by pkoppstein** [comment]
@lixun910 - Thanks for the response.  Unfortunately for the hypothesis, the Lat and Long in the primary table of the SQLite database are both FLOATs with no NULL values.

In case it helps, the CREATE TABLE statements for the two auxiliary tables are as follows:

CREATE TABLE geometry_columns (     f_table_name VARCHAR,      f_geometry_column VARCHAR,      geometry_type INTEGER,      coord_dimension INTEGER,      srid INTEGER,     geometry_format VARCHAR );

CREATE TABLE spatial_ref_sys        (     srid INTEGER UNIQUE,     auth_name TEXT,     auth_srid TEXT,     srtext TEXT);

**Comment by lixun910** [comment]
Thanks for the information!

Does the select and saveas work?

Yes, there are no Null values in SQLite, so that’s why you see points with
lat=0 long=0, which are located on the right side of the map, in your
dataset. And these points are generated because they have empty lat/long
values in original csv file, and should be excluded to create a map that
you expected.

**Comment by pkoppstein** [comment]
@lixun910 - Thanks for the quick response!  You're right that the missing values are the source of the problem, but SQLite does handle them as NULLs - in fact, when I put my thinking cap on, I was able to find them in SQLite using the query: 

    select * from '311_Service_Requests_-_Abandoned_Vehicles'  where Latitude is NULL OR longitude is null;

I was in part misled by GeoDa's "histogram" functionality, which I now realize ignores NULLs, whereas the mapping functionality evidently does not.

So it looks like this "trouble ticket" is turning into an enhancement request (or two) regarding the handling of nulls, especially for lat and long values.

By the way, although I'm just a beginning user of GeoDa, I'm really impressed!

**Comment by lixun910** [comment]
Thanks!

One thing to clarify: the NULL from your query is from the two numeric
columns, not the geomtry column “the_geom” where (0,0) is used and
geometries are coded in wkb.

So, that means we have NULL values in lat and long columns, however when
saved to SQLite these points are saved as (0,0) in geometry column. In
other formats, like ESRI shapefile, NULL geometry is allows so GeoDa will
raise warning of Null geometries when loading the data, which is the
enhancement you mentioned. This is more like a logic issue caused by the
more restrict SQLite format and support of GDAL library.

In histogram, null values will be identified and excluded.

**Comment by pkoppstein** [comment]
@lixun910 - So if I understand you correctly, the problem is in the "GEOMETRY" blob.

But so far as SQLite is concerned, a BLOB is just a BLOB, so I don't see that the limitations of SQLite can explain away the issue. That is, the ability or (inability) to represent the "nulls" in the "GEOMETRY" blob has nothing to do with SQLite.

I'd like to pursue this matter for three reasons:

-   it would be good if some kind of enhancement could be made to GeoDa so that others can avoid this little "glitch"; 
- I'm in the process of assessing how well SQLite is supported by other tools (such as GeoDa);
- I would like to have a better understanding of the implications of SQLite's limits.

Thank you again!

**Comment by lixun910** [comment]
Sounds good. I will take a look into this as well. Thanks for working on this @pkoppstein !!

Yes, it is not attached. Here you go:

https://github.com/lixun910/geoda/files/3488096/Community_Pop.csv.zip
