### ISSUE TITLE
open an csv file

### ISSUE THREAD

**Issue by EagleGeo** [GeoDaCenter/geoda#2209]
Hi, I had problem opening the attached csv file in Geoda, could you please help? Thanks!
[covid_datatest.zip](https://github.com/GeoDaCenter/geoda/files/5165121/covid_datatest.zip)

](url)

**Comment by lixun910** [comment]
@EagleGeo I can't unzip the file you attached. Can you check if the zip file is valid? Thanks!

**Comment by EagleGeo** [comment]
[covid_datatest.zip](https://github.com/GeoDaCenter/geoda/files/5165508/covid_datatest.zip)

Try this one please.

**Comment by lixun910** [comment]
<img width="688" alt="Screen Shot 2020-09-02 at 9 26 34 PM" src="https://user-images.githubusercontent.com/2423887/92071208-00d92f00-ed63-11ea-93ac-76912496986b.png">
@EagleGeo It opens fine on my side. Which version of GeoDao do you use?

**Comment by EagleGeo** [comment]
Looks like that you have join my data to the basemap. Is there a way to open just the csv in Opengeoda and then join it to a basemap? Thanks!

**Comment by jkoschinsky** [comment]
assuming your csv file has XY coordinates, you first need to convert these to points, so you have a spatial file (tools-shape-points from table). Then you can add a basemap.



<https://spatial-data-science-conference.com/>
________________________________

**Comment by jkoschinsky** [comment]
quick clarification since I was referring to "basemap" as the background map you can add to a spatial layer (as in https://geodacenter.github.io/workbook/3a_mapping/lab3a.html#map-base-layer-base-map).

If your question was about how to merge a csv file to a spatial layer, you can also use an ID that is common to the spatial layer and the csv (like a geoID that uniquely identifies each observation). First load the spatial layer, then merge the csv file to it using the common ID through Table-Merge.

<https://spatial-data-science-conference.com/>
________________________________

**Comment by EagleGeo** [comment]
Thanks for the clarification.

Yes, my initial question was about "merge". My problem is that I was not
able to open the csv file. Below is the error message. This is the same csv
that I attached in a previous email.


[image: image.png]

**Comment by jkoschinsky** [comment]
here's a geoJSON version of your file. I could open your csv without a problem in geoda and then map the XY coordinates:
[covid.geojson.zip](https://github.com/GeoDaCenter/geoda/files/5169268/covid.geojson.zip)
The image of the error msg didn't come through.
