### ISSUE TITLE
Shapefile imports fine, but all grayed out

### ISSUE THREAD

**Issue by bhurley-GWU** [GeoDaCenter/geoda#2262]
**From a student (the bug submit was not working):**
_I am two Operating Systems behind 10.14.6 Mojave on a Macbook Pro from 2019 and using the corresponding older version of Geoda (not the two latest releases of Geoda).
Often times when I try to use a tool I will have to select another tool I don't want to use before it will open both of them simultaneously for me to use any functions/ see the tab.
Please reply if needed to Professor Brendan Hurley at hurley@gwu.edu_

**Comment by lixun910** [comment]
@bhurley-GWU Thank you for reporting this! Could you tell us what "tool"
and "another tool" the student mentioned? If possible, a screenshot could
help us to identify the problem quickly. We suggest using the latest GeoDa
1.16 (https://geodacenter.github.io), which has many bugs fixed. Thanks!

However, here is a related issue for an older version of GeoDa (e.g. 1.14,
1.12..) running on a 10.14+ Mac OS: there is a known issue that the map
windows will NOT be popped up after loading a shapfile. Since the map is
not shown and focused, the buttons on the toolbar are not working. To fix
this, one needs to click the GeoDa icon on the taskbar after loading a
shapefile, so that the map will be displayed.

**Comment by bhurley-GWU** [comment]
Ok this worked!
