### ISSUE TITLE
Average Chart doesn't work with space-time with only one time step defined.

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#441]
If only one time step defined, when select in Average Chart, it should behave like a regular variable.

**Comment by jkoschinsky** [comment]
Could you outline the steps to replicate this?

e.g. the example below has 1 time step but not sure what behavior like regular variable means.
<img width="796" alt="screen shot 2016-07-07 at 12 44 08 am" src="https://cloud.githubusercontent.com/assets/13679743/16643631/0b828c60-43dc-11e6-8fdb-65becb5b9d90.png">

**Comment by lixun910** [comment]
Your example defines 2 time periods : time 0 and time 1.  

This issue is for some data with only 1 time period: time 0. The old version behaves incorrectly (can't remember, but you can replicate it in eg 1.8.7.9)

**Comment by jkoschinsky** [comment]
But then you're using a regular variable that wasn't grouped, right, since
the variable editor requires a minimum of two variables/time periods to
proceed.

On 7 July 2016 at 00:58, Xun Li <notifications@github.com> wrote:

> Your example defines 2 time periods : time 0 and time 1.
>
> This issue is for some data with only 1 time period: time 0. The old
> version behaves incorrectly (can't remember, but you can replicate it in eg
> 1.8.7.9)
>
> > On Jul 6, 2016, at 10:45 PM, jkoschinsky <notifications@github.com>
> wrote:
> >
> > Could you outline the steps to replicate this?
> >
> > e.g. the example below has 1 time step but not sure what behavior like
> regular variable means.
> >
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/GeoDaCenter/geoda/issues/441#issuecomment-230986093>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANC8f-QQl2xCtY-6l6T0NbAIxyHWlAnNks5qTJV7gaJpZM4IoEXy>
> .
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by jkoschinsky** [comment]
Verified in GeoDa 1.8.8 (OSX Yosemite, 10.10.5).
works with ungrouped variable:

<img width="799" alt="screen shot 2016-07-07 at 1 05 07 am" src="https://cloud.githubusercontent.com/assets/13679743/16643988/093a048a-43df-11e6-9d14-9b7e5f9c0dfd.png">
