### ISSUE TITLE
Replicable crash: weights creation

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#500]
GeoDa 1.8.13.9, Mac OSX
[graz.zip](https://github.com/GeoDaCenter/geoda/files/537189/graz.zip) - has missing values

Steps:
1. Load Graz.shop
2. create queen weights
2. when trying to save the file, GeoDa crashes (replicable)

**Comment by lixun910** [comment]
this shapefile not only has missing values, some of the polygons are also not valid -- which means its outside the bounding box of the entire shapefile.

Weights creating function can't handle such case.

One solution is raise "invalid geometry" warning instead of crashing, and suggest user to "export valid geometries to another file"

Any idea?

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.5 — Mac OSX
Confirmed fix.
