### ISSUE TITLE
add real-time weights creation when brush moran scatter plot

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/geoda#505]

**Comment by jkoschinsky** [comment]
from Luc: 
Just want to make sure, the points in the scatter plot change on the fly as well? Maybe they should be colored as selected unselected? Since the weights for the selected/unselected change, the corresponding x, Wx pairs change as well so the scatter moves. The original scatter points could be used as reference, but the new lines fit the new points, not the selected-unselected points from the original scatter. So in addition to the original scatter, the new scatter should be shown with the proper fit for each line. However, this may be problematic as the selection changes dynamically.

Xun:
Yes, the calculations are already done. Only need a way to viz. I think I have a solution to do it: have three sets of points on Moran scatter plot for all/sel/unselected with different color, and use transparency to distinguish them, and user can click on the Moran values (legends) to highlight one set points and faded other sets. Will add a demo in 1.8.15.x and then we can discuss.

Julia:
Don't think this is implemented in GeoDa 1.8.15.5, right?

<img width="531" alt="screen shot 2016-12-20 at 3 25 11 pm" src="https://cloud.githubusercontent.com/assets/13679743/21368515/85c32650-c6c8-11e6-8788-80baaea91bd4.png">

**Comment by jkoschinsky** [comment]
This is great! You might still be working on this but FYI for GeoDa 1.8.15.9 — Mac OSX:

The Moran's I values in the scatter plots and the randomization views sometimes don't match, e.g. see these two examples:

<img width="1831" alt="screen shot 2017-01-13 at 7 39 32 am" src="https://cloud.githubusercontent.com/assets/13679743/21932054/3144a988-d964-11e6-866c-42fa5a910412.png">

<img width="1386" alt="screen shot 2017-01-13 at 7 43 36 am" src="https://cloud.githubusercontent.com/assets/13679743/21932060/341bfa4e-d964-11e6-865a-f77409078bd4.png">

Also, when you resize the Moran scatterplot view with the two selected/unselected plots on each side of the main plot, the subset plots that were there (top image) disappear (bottom image):

<img width="1609" alt="screen shot 2017-01-13 at 7 39 10 am" src="https://cloud.githubusercontent.com/assets/13679743/21932089/5de5d93a-d964-11e6-86b3-83cf0672f263.png">

<img width="859" alt="screen shot 2017-01-13 at 7 38 53 am" src="https://cloud.githubusercontent.com/assets/13679743/21932096/65948ee2-d964-11e6-8fba-54e3debad369.png">

**Comment by jkoschinsky** [comment]
GeoDa 1.8.15.13 — Mac OSX
Confirmed fix:

<img width="1591" alt="screen shot 2017-01-23 at 7 29 11 pm" src="https://cloud.githubusercontent.com/assets/13679743/22230289/43fb0fcc-e1a2-11e6-9c80-e2a3de6b9a03.png">
