### ISSUE TITLE
No way to view Univariate Moran's I scatterplot statistics

### ISSUE THREAD

**Issue by pbreach** [GeoDaCenter/geoda#595]
I am not sure if this is intended, however it seems that there is no option to view summary statistics of the regression line on the Moran's I scatterplot. Here is a screen clip of the options that are shown for the scatterplot:

![image](https://cloud.githubusercontent.com/assets/8889265/22836596/14a6c288-ef8b-11e6-85c9-c3e0195a9e1d.png)

There doesn't seem to be any option to view statistics as in the case of a typical scatter plot. Am I missing something? In previous versions of GEODA this was included. I am currently using 1.8.12 on Windows downloaded from http://geodacenter.github.io/download.html.

**Comment by jkoschinsky** [comment]
We took this out because the p-values are incorrect (you can access the
correct ones though right-click -- randomization) .
However, if you're aware of this and still want to view the stats below the
scatterplot, right-click on the Moran Scatterplot, save results and open
those two variables in the regular scatterplot.
