### ISSUE TITLE
cache.sqlite located in room directory

### ISSUE THREAD

**Issue by xianwenchen** [GeoDaCenter/geoda#623]
Hi!

I am trying to re-pack the .deb installation file for Arch Linux. I noticed that cache.sqlite is in the root file. 

This is a problem. Say when the geoda is located in /usr/geoda folder. A normal user should not have access to /usr/geoda/cache.sqlite. Rather, a normal user should have their own cache.sqlite in their home directory.

Is there some way to fix it, by e.g. an environmental variable?

**Comment by lixun910** [comment]
We don't have the feature at current release to change env setting for cache.sqlite file. But I don't think you need to if this is for lab installation: GeoDa doesn't need to be installed under /user, you can put/copy GeoDa directory to a safe folder that normal user can access.

Let me know if this helps.

Thanks!

**Comment by xianwenchen** [comment]
Thank you.

This workaround will be okay, of course.

It is an important issue for a centralized server environment, because we would like to have one location to store the program files, and every user uses these program files. However, it may be a problem, when multiple users have access to the folder and write to cache.sqlite at the same time, right?

Another issue is package management. I am creating a package in the AUR repository for Arch Linux so that users of Arch Linux can install GeoDa and update GeoDa as any other package in the AUR repository. Maintaining a copy in home directory manually is not ideal.

**Comment by lixun910** [comment]
Yes, you are correct. GeoDa desktop (<= 1.8.14) does not support installation on a centralized server environment. I will leave this issue as an open ticket and we plan to fix it in next release.

For your information: it will be ok if you plan to deploy current release 1.8.14, since it is not an issue for multiple user writing to cache.sqlite, which supports concurrency. The cache.sqlite used in version 1.8.14 is for only auto-completion feature (in connect datasource dialog).

Will keep you updated. Thanks!

**Comment by lixun910** [comment]
This issue will be addressed in GeoDa 1.14. The cache.sqlite file will be located in room directory on Ubuntu.
