### ISSUE TITLE
Crash when creating a rates-calculated map

### ISSUE THREAD

**Issue by YidanJ-Wu** [GeoDaCenter/geoda#821]
Version 1.8.16.25
Windows 8 

Map > Rates-Calculated Map > Raw Rates
![image](https://cloud.githubusercontent.com/assets/22801047/26030693/89c879da-381f-11e7-88c8-da731fab8db9.png)

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.16.27
Windows 8
Fixed!
![image](https://cloud.githubusercontent.com/assets/22801047/26067290/4b7f492e-395f-11e7-9f38-3e26fc1d025b.png)

**Comment by YidanJ-Wu** [comment]
GeoDa 1.8.16.27
Windows 8

Map > Rates Calculated Map > Raw Rates
Did this after deleting some values in the Stipend10 column. 

![image](https://cloud.githubusercontent.com/assets/22801047/26078878/7eea8ea0-3986-11e7-9de1-ff6dd1f6d27c.png)

![image](https://cloud.githubusercontent.com/assets/22801047/26078802/4803d536-3986-11e7-9d3a-7a8b05a182cf.png)

**Comment by lixun910** [comment]
Yes, this is working as expected

**Comment by YidanJ-Wu** [comment]
1.8.16.29
Windows 8

Confirmed

**Comment by lixun910** [comment]
Thanks again, Julie!!

This is another “old” bug that has been “activated” due to upgrade to wxWidgets 3.1, which is more strict on its drawing functions.

When the movie is playing, open a new map will crash iif there are many polygons to draw. Because the map is not ready to paint, but the movie player is calling it’s paint function. A check flag should be added to guarantee that only draw the map when its ready.

Fixed in #69451a7

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
