### ISSUE TITLE
Hierarchical cluster bug

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#836]
From Marynia:
it seems the same issue with geometric centroids was there -- previously it was in the K-cluster, but the recent version of GeoDa fixed that. Now, just see the spatial centroid inclusion swamping the hierarchical clustering.

![hierarchical cluster bug](https://cloud.githubusercontent.com/assets/13679743/26229999/4a677332-3c0b-11e7-9d45-7e9f0e10777b.png)

**Comment by lixun910** [comment]
Hi Julia

This should be fixed in the latest GeoDa (adding "data transformation" to
standardize data in Hierachical clustering). I don't think Marynia has the
latest version:
https://www.dropbox.com/s/k79c2ifjn0iycir/GeoDa1.8.16.27-Installer.dmg?dl=0

Xun Li, Ph.D

Assistant Director for Data Science
Center for Spatial Data Science
University of Chicago
http://spatial.uchicago.edu

**Comment by jkoschinsky** [comment]
GeoDa 1.8.16.33 — Mac OSX
Verified.
