### ISSUE TITLE
Animation won't pause

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/geoda#866]
GeoDa 1.8.16.31 — Mac OSX
Ghana data

I had a lot of views open, then started animation and tried to pause but there was no response to the pause request, it just kept running. Had to force-quit to get out:

<img width="961" alt="screen shot 2017-05-27 at 10 19 19 pm" src="https://cloud.githubusercontent.com/assets/13679743/26525878/c4341ec4-432a-11e7-8e1a-bbcf602dbedc.png">

Also, cosmetic formatting point: Let's move the min and max amounts further apart (and may be use scientific notation if length is exceeded or put max below min to avoid current overlap:

<img width="540" alt="screen shot 2017-05-27 at 10 18 26 pm" src="https://cloud.githubusercontent.com/assets/13679743/26525895/0c20ffd6-432b-11e7-8494-ce53af7f7ad7.png">

**Comment by lixun910** [comment]
Can't replicate this issue. Is it possible that you have "Scatter plot variables" dialog opened? because this windows is NOT a modeless and you have to close it first to access to other window (e.g. the Animation dialog). Or, it could be too many windows are opened, and there will be a lag after you click "pause" button because the action will act after all opened window executed current time step.

Will keep this open. Also will fix the label issue in next release.

**Comment by jkoschinsky** [comment]
ok, will try to replicate -- yes, both of your explanations make sense in
that context.

**Comment by jkoschinsky** [comment]
keeping open bc of min overlap labeling
